const users = [
    {
      id: 1,
      name: 'John Doe',
      age: 25,
      email: 'john@example.com',
      country: 'USA',
      company: 'ABC Inc.',
      birthday: '1999-05-15',
    },
    {
      id: 2,
      name: 'Jane Smith',
      age: 30,
      email: 'jane@example.com',
      country: 'Canada',
      company: 'XYZ Corp.',
      birthday: '1992-12-10',
    },
    {
      id: 3,
      name: 'Alice Johnson',
      age: 28,
      email: 'alice@example.com',
      country: 'UK',
      company: '123 Solutions',
      birthday: '1994-08-22',
    },
    {
      id: 4,
      name: 'Bob Williams',
      age: 35,
      email: 'bob@example.com',
      country: 'Australia',
      company: 'Tech Innovators',
      birthday: '1989-03-05',
    },
    {
      id: 5,
      name: 'Eva Davis',
      age: 22,
      email: 'eva@example.com',
      country: 'Germany',
      company: 'Global Industries',
      birthday: '2002-11-18',
    },
    {
      id: 6,
      name: 'David Brown',
      age: 40,
      email: 'david@example.com',
      country: 'France',
      company: 'Dynamic Systems',
      birthday: '1982-06-30',
    },
    {
      id: 7,
      name: 'Sophie Miller',
      age: 26,
      email: 'sophie@example.com',
      country: 'Spain',
      company: 'Mega Enterprises',
      birthday: '1996-09-12',
    },
    {
      id: 8,
      name: 'Michael Wilson',
      age: 32,
      email: 'michael@example.com',
      country: 'Brazil',
      company: 'Infinite Solutions',
      birthday: '1989-12-28',
    },
    {
      id: 9,
      name: 'Olivia Lee',
      age: 29,
      email: 'olivia@example.com',
      country: 'Japan',
      company: 'Ninja Tech',
      birthday: '1993-04-01',
    },
    {
      id: 10,
      name: 'Daniel Kim',
      age: 27,
      email: 'daniel@example.com',
      country: 'South Korea',
      company: 'Future Innovations',
      birthday: '1995-07-08',
    },
  ];
  
  export default users;